# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialognfCxyc.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(672, 569)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.lblOriginal = QLabel(Dialog)
        self.lblOriginal.setObjectName(u"lblOriginal")
        self.lblOriginal.setGeometry(QRect(340, 40, 320, 240))
        self.lblOriginal.setFrameShape(QFrame.Box)
        self.lblHSV = QLabel(Dialog)
        self.lblHSV.setObjectName(u"lblHSV")
        self.lblHSV.setGeometry(QRect(10, 320, 320, 240))
        self.lblHSV.setFrameShape(QFrame.Box)
        self.lblOutput = QLabel(Dialog)
        self.lblOutput.setObjectName(u"lblOutput")
        self.lblOutput.setGeometry(QRect(340, 320, 320, 240))
        self.lblOutput.setFrameShape(QFrame.Box)
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(346, 10, 311, 20))
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 290, 321, 20))
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(340, 290, 321, 20))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.btnFromFile = QPushButton(Dialog)
        self.btnFromFile.setObjectName(u"btnFromFile")
        self.btnFromFile.setGeometry(QRect(10, 10, 75, 23))
        self.btnFromCamera = QPushButton(Dialog)
        self.btnFromCamera.setObjectName(u"btnFromCamera")
        self.btnFromCamera.setGeometry(QRect(250, 10, 75, 23))
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 40, 321, 111))
        self.sldHMin = QSlider(self.groupBox)
        self.sldHMin.setObjectName(u"sldHMin")
        self.sldHMin.setGeometry(QRect(60, 20, 191, 22))
        self.sldHMin.setMaximum(179)
        self.sldHMin.setOrientation(Qt.Horizontal)
        self.sldSMin = QSlider(self.groupBox)
        self.sldSMin.setObjectName(u"sldSMin")
        self.sldSMin.setGeometry(QRect(60, 50, 191, 22))
        self.sldSMin.setMaximum(255)
        self.sldSMin.setOrientation(Qt.Horizontal)
        self.sldVMin = QSlider(self.groupBox)
        self.sldVMin.setObjectName(u"sldVMin")
        self.sldVMin.setGeometry(QRect(60, 80, 191, 22))
        self.sldVMin.setMaximum(255)
        self.sldVMin.setOrientation(Qt.Horizontal)
        self.leHMin = QLineEdit(self.groupBox)
        self.leHMin.setObjectName(u"leHMin")
        self.leHMin.setGeometry(QRect(260, 20, 51, 20))
        self.leSMin = QLineEdit(self.groupBox)
        self.leSMin.setObjectName(u"leSMin")
        self.leSMin.setGeometry(QRect(260, 50, 51, 20))
        self.leVMin = QLineEdit(self.groupBox)
        self.leVMin.setObjectName(u"leVMin")
        self.leVMin.setGeometry(QRect(260, 80, 51, 20))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 20, 51, 21))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 50, 51, 21))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 80, 51, 21))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 170, 321, 111))
        self.sldHMax = QSlider(self.groupBox_2)
        self.sldHMax.setObjectName(u"sldHMax")
        self.sldHMax.setGeometry(QRect(60, 20, 191, 22))
        self.sldHMax.setMaximum(179)
        self.sldHMax.setValue(179)
        self.sldHMax.setOrientation(Qt.Horizontal)
        self.sldSMax = QSlider(self.groupBox_2)
        self.sldSMax.setObjectName(u"sldSMax")
        self.sldSMax.setGeometry(QRect(60, 50, 191, 22))
        self.sldSMax.setMaximum(255)
        self.sldSMax.setValue(255)
        self.sldSMax.setOrientation(Qt.Horizontal)
        self.sldVMax = QSlider(self.groupBox_2)
        self.sldVMax.setObjectName(u"sldVMax")
        self.sldVMax.setGeometry(QRect(60, 80, 191, 22))
        self.sldVMax.setMaximum(255)
        self.sldVMax.setValue(255)
        self.sldVMax.setOrientation(Qt.Horizontal)
        self.leVMax = QLineEdit(self.groupBox_2)
        self.leVMax.setObjectName(u"leVMax")
        self.leVMax.setGeometry(QRect(260, 80, 51, 20))
        self.leHMax = QLineEdit(self.groupBox_2)
        self.leHMax.setObjectName(u"leHMax")
        self.leHMax.setGeometry(QRect(260, 20, 51, 20))
        self.leSMax = QLineEdit(self.groupBox_2)
        self.leSMax.setObjectName(u"leSMax")
        self.leSMax.setGeometry(QRect(260, 50, 51, 20))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 20, 51, 21))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 80, 51, 21))
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 50, 51, 21))
        self.label_12.setAlignment(Qt.AlignCenter)
        self.comboBox = QComboBox(Dialog)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(180, 10, 61, 22))
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 10, 61, 20))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Thresholder", None))
        self.lblOriginal.setText("")
        self.lblHSV.setText("")
        self.lblOutput.setText("")
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Original", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"HSV", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Output", None))
        self.btnFromFile.setText(QCoreApplication.translate("Dialog", u"From File", None))
        self.btnFromCamera.setText(QCoreApplication.translate("Dialog", u"From Camera", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Lower Band", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"H Min", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"S Min", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"V Min", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Higher Band", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"H Max", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"V Max", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"S Max", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Camera No:", None))
    # retranslateUi

